### ISSUE TITLE
Tests worked fine until i randomly started getting errors? (i didn't change the workflow)

### ISSUE THREAD

**Issue by TheEt1234** [BuckarooBanzay/mtt#13]
/entrypoint.sh: line 79: minetestserver: command not found
See: https://github.com/TheEt1234/skyblock_zero/actions/runs/11540892550/job/32122244454

https://github.com/TheEt1234/skyblock_zero/actions

Maybe this has something to do with the rename and the fact that its not called minetest anymore(?)

**Comment by BuckarooBanzay** [comment]
nice, this was caused by https://github.com/minetest/minetest/commit/4b90e582b42c4881860100b10a9572d8d33a39da
the binary name was changed, PR #14 should fix that

thanks for the report :+1:

**Comment by BuckarooBanzay** [comment]
i think i'm versioning this along with stable minetest/luanti releases from now on
